export const RouteIndex = "/"
export const RouteDashboard = "/dashboard"
export const RouteLogin = "/login"
export const RouteRegister = "/register"
export const RouteProducts = "/products"
export const RouteSuppliers = "/suppliers"
export const RouteCategories = "/categories"
export const RouteStockmovements = "/stockmovements"